version: '3.9'

services:
 api-service: 
   container_name: api-container-1
   build:
    context: ./
    dockerfile: Dockerfile 
   environment:
    API_TITLE: Api docs dev
   ports:
    - 8060:8080
   networks:
    - backend
#  api-service-test: 
#    container_name: api-container-2
#    build:
#     context: ./
#     dockerFile: Dockerfile 
#    ports:
#     - 8070:8080
#    networks:
#     - backend
#  api-service-prod: 
#    container_name: api-container-3
#    image: api-image-sample 
#    ports:
#     - 8090:8080
#    networks:
#     - backend
 redis:
   image: redis:6.2-alpine
   container_name: redis
   hostname: redis
   ports:
     - '6379:6379'
   environment: 
     - ALLOW_EMPTY_PASSWORD=yes
     - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
   networks:
     - backend
networks:
 backend:
  driver: bridge